CREATE DATABASE IF NOT EXISTS `login` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `login`;

CREATE TABLE `login` (
  `ID` tinyint(4) NOT NULL,
  `L1` varchar(25) NOT NULL DEFAULT '',
  `L2` varchar(255) NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE `login`
  ADD PRIMARY KEY (`ID`);

ALTER TABLE `login`
  MODIFY `ID` tinyint(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;
